LinkLuaModifier("modifier_pvp_damage_layers", "modifiers/modifier_pvp_damage_layers", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_spawn_healing", "modifiers/modifier_spawn_healing", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_aghanim_crystal_activator", "modifiers/modifier_aghanim_crystal_activator", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_damage_reduction_custom", "modifiers/modifier_damage_reduction_custom", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_new_game_plus_thinker", "modifiers/modifier_new_game_plus_thinker", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_garbage_collector_fix", "modifiers/modifier_garbage_collector_fix", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_creep_antilag_phased", "modifiers/modifier_creep_antilag", LUA_MODIFIER_MOTION_NONE)

LinkLuaModifier("modifier_evil_citadel", "modifiers/modifier_evil_citadel", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_limited_lives", "modifiers/modifier_limited_lives", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_dummy_target", "modifiers/modifier_dummy_target", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gold_bank", "modifiers/modifier_gold_bank", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_outpost_capture", "modifiers/modifier_outpost_capture", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_timmy", "modifiers/modifier_timmy", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_meepo", "modifiers/modifier_meepo", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_chicken", "modifiers/modifier_chicken", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_aghanim_portal", "modifiers/modifier_aghanim_portal", LUA_MODIFIER_MOTION_NONE)

LinkLuaModifier("modifier_scaling_damage_reduction", "modifiers/modifier_scaling_damage_reduction", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_new_game_plus_magical_resistance", "modifiers/modifier_new_game_plus_magical_resistance", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_hero_stats_manager_player", "modules/hero_stats_manager/HeroStatsManager.lua", LUA_MODIFIER_MOTION_NONE)

-- Buffs and boons --
LinkLuaModifier("modifier_player_difficulty_buff_gold_50", "modifiers/modes/buffs/easy/modifier_player_difficulty_buff_gold_50", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_player_difficulty_buff_heal_on_kill_25", "modifiers/modes/buffs/easy/modifier_player_difficulty_buff_heal_on_kill_25", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_player_difficulty_buff_damage_reduction_50", "modifiers/modes/buffs/easy/modifier_player_difficulty_buff_damage_reduction_50", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_player_difficulty_buff_armor_50", "modifiers/modes/buffs/easy/modifier_player_difficulty_buff_armor_50", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_player_difficulty_buff_damage_25", "modifiers/modes/buffs/easy/modifier_player_difficulty_buff_damage_25", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_player_difficulty_buff_bounty_rune_200", "modifiers/modes/buffs/easy/modifier_player_difficulty_buff_bounty_rune_200", LUA_MODIFIER_MOTION_NONE)

LinkLuaModifier("modifier_player_difficulty_buff_bounty_rune_50", "modifiers/modes/buffs/normal/modifier_player_difficulty_buff_bounty_rune_50", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_player_difficulty_buff_gold_10", "modifiers/modes/buffs/normal/modifier_player_difficulty_buff_gold_10", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_player_difficulty_buff_heal_on_kill_10", "modifiers/modes/buffs/normal/modifier_player_difficulty_buff_heal_on_kill_10", LUA_MODIFIER_MOTION_NONE)

LinkLuaModifier("modifier_apocalypse_corpse_explosion", "modifiers/apocalypse_modifiers/corpse_explosion", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_apocalypse_increased_speed", "modifiers/apocalypse_modifiers/increased_speed", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_apocalypse_attack_range", "modifiers/apocalypse_modifiers/attack_range", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_apocalypse_armor", "modifiers/apocalypse_modifiers/armor", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_apocalypse_magic_resistance", "modifiers/apocalypse_modifiers/magic_resistance", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_apocalypse_evasion", "modifiers/apocalypse_modifiers/evasion", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_apocalypse_magic_attacks", "modifiers/apocalypse_modifiers/magic_attacks", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_apocalypse_mana_burn", "modifiers/apocalypse_modifiers/mana_burn", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_apocalypse_life_blood", "modifiers/apocalypse_modifiers/life_blood", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_apocalypse_rushing", "modifiers/apocalypse_modifiers/rushing", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_apocalypse_health_deny", "modifiers/apocalypse_modifiers/health_deny", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_apocalypse_magic_shield", "modifiers/apocalypse_modifiers/magic_shield", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_apocalypse_mana_void", "modifiers/apocalypse_modifiers/mana_void", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_apocalypse_reanimation", "modifiers/apocalypse_modifiers/reanimation", LUA_MODIFIER_MOTION_NONE)

LinkLuaModifier("modifier_player_buffs_enemy_explosion", "modifiers/player_buffs/modifier_player_buffs_enemy_explosion", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_player_buffs_adrenaline", "modifiers/player_buffs/modifier_player_buffs_adrenaline", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_player_buffs_critical_strike", "modifiers/player_buffs/modifier_player_buffs_critical_strike", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_player_buffs_attack_sacrifice", "modifiers/player_buffs/modifier_player_buffs_attack_sacrifice", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_player_buffs_spell_sacrifice", "modifiers/player_buffs/modifier_player_buffs_spell_sacrifice", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_player_buffs_sanguine_clarity", "modifiers/player_buffs/modifier_player_buffs_sanguine_clarity", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_player_buffs_omniscent_blessing", "modifiers/player_buffs/modifier_player_buffs_omniscent_blessing", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_player_buffs_vulnerable", "modifiers/player_buffs/modifier_player_buffs_vulnerable", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_player_buffs_glasscannon", "modifiers/player_buffs/modifier_player_buffs_glasscannon", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_player_buffs_status_boost", "modifiers/player_buffs/modifier_player_buffs_status_boost", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_player_buffs_hard_exterior", "modifiers/player_buffs/modifier_player_buffs_hard_exterior", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_player_buffs_blood_pool", "modifiers/player_buffs/modifier_player_buffs_blood_pool", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_player_buffs_vitality_curse", "modifiers/player_buffs/modifier_player_buffs_vitality_curse", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_player_buffs_mana_curse", "modifiers/player_buffs/modifier_player_buffs_mana_curse", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_player_buffs_drunken_brawler", "modifiers/player_buffs/modifier_player_buffs_drunken_brawler", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_player_buffs_bloodthirsty_killer", "modifiers/player_buffs/modifier_player_buffs_bloodthirsty_killer", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_magic_resist_reduction", "modifiers/modifier_reduction", LUA_MODIFIER_MOTION_NONE)

LinkLuaModifier("modifier_dummy_wearable_hero", "modifiers/modifier_dummy_wearable_hero", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_walking_animation_fix", "modifiers/modifier_walking_animation_fix", LUA_MODIFIER_MOTION_NONE)

LinkLuaModifier("modifier_wave_manager_unit_ai", "modules/wave_manager/WaveManager", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_wave_manager_player", "modules/wave_manager/WaveManager", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_wave_manager_player_attribute_debuff", "modules/wave_manager/WaveManager", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_wave_manager_fow_revealer", "modules/wave_manager/WaveManager", LUA_MODIFIER_MOTION_NONE)

LinkLuaModifier("modifier_max_movement_speed", "modifiers/modifier_max_movement_speed", LUA_MODIFIER_MOTION_NONE)

LinkLuaModifier("modifier_season_shock", "modifiers/seasons/modifier_season_shock", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_season_frenzy", "modifiers/seasons/modifier_season_frenzy", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_season_firestorm", "modifiers/seasons/modifier_season_firestorm", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_season_death", "modifiers/seasons/modifier_season_death", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_season_lightning", "modifiers/seasons/modifier_season_lightning", LUA_MODIFIER_MOTION_NONE)

LinkLuaModifier("modifier_xp_intellect_talent_1", "abilities/talents/intellect/xp_intellect_talent_1", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_intellect_talent_2", "abilities/talents/intellect/xp_intellect_talent_2", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_intellect_talent_3", "abilities/talents/intellect/xp_intellect_talent_3", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_intellect_talent_4", "abilities/talents/intellect/xp_intellect_talent_4", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_intellect_talent_7", "abilities/talents/intellect/xp_intellect_talent_7", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_intellect_talent_8", "abilities/talents/intellect/xp_intellect_talent_8", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_intellect_talent_9", "abilities/talents/intellect/xp_intellect_talent_9", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_intellect_talent_10", "abilities/talents/intellect/xp_intellect_talent_10", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_intellect_talent_12", "abilities/talents/intellect/xp_intellect_talent_12", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_intellect_talent_13", "abilities/talents/intellect/xp_intellect_talent_13", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_intellect_talent_14", "abilities/talents/intellect/xp_intellect_talent_14", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_intellect_talent_15", "abilities/talents/intellect/xp_intellect_talent_15", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_intellect_talent_17", "abilities/talents/intellect/xp_intellect_talent_17", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_intellect_talent_18", "abilities/talents/intellect/xp_intellect_talent_18", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_intellect_talent_20", "abilities/talents/intellect/xp_intellect_talent_20", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_intellect_talent_23", "abilities/talents/intellect/xp_intellect_talent_23", LUA_MODIFIER_MOTION_NONE)

LinkLuaModifier("modifier_xp_strength_talent_1", "abilities/talents/strength/xp_strength_talent_1", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_strength_talent_2", "abilities/talents/strength/xp_strength_talent_2", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_strength_talent_3", "abilities/talents/strength/xp_strength_talent_3", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_strength_talent_4", "abilities/talents/strength/xp_strength_talent_4", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_strength_talent_5", "abilities/talents/strength/xp_strength_talent_5", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_strength_talent_7", "abilities/talents/strength/xp_strength_talent_7", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_strength_talent_8", "abilities/talents/strength/xp_strength_talent_8", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_strength_talent_9", "abilities/talents/strength/xp_strength_talent_9", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_strength_talent_10", "abilities/talents/strength/xp_strength_talent_10", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_strength_talent_11", "abilities/talents/strength/xp_strength_talent_11", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_strength_talent_12", "abilities/talents/strength/xp_strength_talent_12", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_strength_talent_13", "abilities/talents/strength/xp_strength_talent_13", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_strength_talent_14", "abilities/talents/strength/xp_strength_talent_14", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_strength_talent_15", "abilities/talents/strength/xp_strength_talent_15", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_strength_talent_17", "abilities/talents/strength/xp_strength_talent_17", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_strength_talent_18", "abilities/talents/strength/xp_strength_talent_18", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_strength_talent_20", "abilities/talents/strength/xp_strength_talent_20", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_strength_talent_23", "abilities/talents/strength/xp_strength_talent_23", LUA_MODIFIER_MOTION_NONE)

LinkLuaModifier("modifier_xp_agility_talent_1", "abilities/talents/agility/xp_agility_talent_1", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_agility_talent_2", "abilities/talents/agility/xp_agility_talent_2", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_agility_talent_3", "abilities/talents/agility/xp_agility_talent_3", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_agility_talent_4", "abilities/talents/agility/xp_agility_talent_4", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_agility_talent_5", "abilities/talents/agility/xp_agility_talent_5", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_agility_talent_6", "abilities/talents/agility/xp_agility_talent_6", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_agility_talent_7", "abilities/talents/agility/xp_agility_talent_7", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_agility_talent_8", "abilities/talents/agility/xp_agility_talent_8", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_agility_talent_9", "abilities/talents/agility/xp_agility_talent_9", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_agility_talent_10", "abilities/talents/agility/xp_agility_talent_10", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_agility_talent_11", "abilities/talents/agility/xp_agility_talent_11", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_agility_talent_12", "abilities/talents/agility/xp_agility_talent_12", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_agility_talent_13", "abilities/talents/agility/xp_agility_talent_13", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_agility_talent_14", "abilities/talents/agility/xp_agility_talent_14", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_agility_talent_15", "abilities/talents/agility/xp_agility_talent_15", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_agility_talent_16", "abilities/talents/agility/xp_agility_talent_16", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_agility_talent_17", "abilities/talents/agility/xp_agility_talent_17", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_agility_talent_18", "abilities/talents/agility/xp_agility_talent_18", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_agility_talent_20", "abilities/talents/agility/xp_agility_talent_20", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_agility_talent_23", "abilities/talents/agility/xp_agility_talent_23", LUA_MODIFIER_MOTION_NONE)

LinkLuaModifier("modifier_xp_all_talent_1", "abilities/talents/all/xp_all_talent_1", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_all_talent_2", "abilities/talents/all/xp_all_talent_2", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_all_talent_3", "abilities/talents/all/xp_all_talent_3", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_all_talent_4", "abilities/talents/all/xp_all_talent_4", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_all_talent_5", "abilities/talents/all/xp_all_talent_5", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_all_talent_6", "abilities/talents/all/xp_all_talent_6", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_all_talent_7", "abilities/talents/all/xp_all_talent_7", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_all_talent_8", "abilities/talents/all/xp_all_talent_8", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_all_talent_9", "abilities/talents/all/xp_all_talent_9", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_all_talent_10", "abilities/talents/all/xp_all_talent_10", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_all_talent_11", "abilities/talents/all/xp_all_talent_11", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_all_talent_12", "abilities/talents/all/xp_all_talent_12", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_all_talent_13", "abilities/talents/all/xp_all_talent_13", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_all_talent_14", "abilities/talents/all/xp_all_talent_14", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_all_talent_15", "abilities/talents/all/xp_all_talent_15", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_all_talent_16", "abilities/talents/all/xp_all_talent_16", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_all_talent_17", "abilities/talents/all/xp_all_talent_17", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_all_talent_18", "abilities/talents/all/xp_all_talent_18", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_all_talent_20", "abilities/talents/all/xp_all_talent_20", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_all_talent_23", "abilities/talents/all/xp_all_talent_23", LUA_MODIFIER_MOTION_NONE)

LinkLuaModifier("modifier_xp_manager_player", "modules/xp_manager/XpManager", LUA_MODIFIER_MOTION_NONE)

LinkLuaModifier("modifier_auto_pickup", "modifiers/modifier_auto_pickup", LUA_MODIFIER_MOTION_NONE)


LinkLuaModifier("modifier_happy_new_year", "modifiers/modifier_happy_new_year", LUA_MODIFIER_MOTION_NONE)

LinkLuaModifier("modifier_twin_gate_custom", "modifiers/modifier_twin_gate_custom", LUA_MODIFIER_MOTION_NONE)

LinkLuaModifier("modifier_aghanim_tower", "modifiers/modifier_aghanim_tower", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_uber_bosses_portal", "modifiers/modifier_uber_bosses_portal", LUA_MODIFIER_MOTION_NONE)

-- Runes --
LinkLuaModifier("modifier_item_socket_rune_legendary_drow_ranger_multishot", "modifiers/runes/heroes/drow_ranger/modifier_item_socket_rune_legendary_drow_ranger_multishot", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_item_socket_rune_legendary_drow_ranger_marksmanship", "modifiers/runes/heroes/drow_ranger/modifier_item_socket_rune_legendary_drow_ranger_marksmanship", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_item_socket_rune_legendary_medusa_split_shot", "modifiers/runes/heroes/medusa/modifier_item_socket_rune_legendary_medusa_split_shot", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_item_socket_rune_legendary_faceless_void_time_lock", "modifiers/runes/heroes/faceless_void/modifier_item_socket_rune_legendary_faceless_void_time_lock", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_item_socket_rune_legendary_faceless_void_chronosphere", "modifiers/runes/heroes/faceless_void/modifier_item_socket_rune_legendary_faceless_void_chronosphere", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_item_socket_rune_legendary_lina_light_strike_array", "modifiers/runes/heroes/lina/modifier_item_socket_rune_legendary_lina_light_strike_array", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_item_socket_rune_legendary_tidehunter_anchor_smash", "modifiers/runes/heroes/tidehunter/modifier_item_socket_rune_legendary_tidehunter_anchor_smash", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_item_socket_rune_legendary_axe_counter_helix", "modifiers/runes/heroes/axe/modifier_item_socket_rune_legendary_axe_counter_helix", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_item_socket_rune_legendary_axe_culling_blade", "modifiers/runes/heroes/axe/modifier_item_socket_rune_legendary_axe_culling_blade", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_item_socket_rune_legendary_luna_moon_beam", "modifiers/runes/heroes/luna/modifier_item_socket_rune_legendary_luna_moon_beam", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_item_socket_rune_legendary_lone_druid_bear", "modifiers/runes/heroes/lone_druid/modifier_item_socket_rune_legendary_lone_druid_bear", LUA_MODIFIER_MOTION_NONE)

LinkLuaModifier("modifier_hero_tanya", "heroes/hero_tanya/modifier_hero_tanya", LUA_MODIFIER_MOTION_NONE)

LinkLuaModifier("modifier_boss_arc_warden_ai", "heroes/bosses/arc_warden/ai", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_item_manager_player", "modules/item_manager/ItemManager.lua", LUA_MODIFIER_MOTION_NONE)